apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
stringData:
  email-username: "umerleghari01@gmail.com"
  email-password: "adhgycuxbulkukts"
type: Opaque
